services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: esprit123
      MYSQL_DATABASE: timesheetdb
    ports:
      - "3306:3306"
    volumes:
      - timesheetvol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pesprit123"]
      interval: 10s
      timeout: 5s
      retries: 5

  timesheet:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: salmabm45/timesheet-salmabenmiled-2lainfo1:latest
    restart: "no"
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/timesheetdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: esprit123
    stdin_open: true
    tty: true

volumes:
  timesheetvol:
